# -*- coding: utf-8 -*-
"""wordcloud.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GKy6BDL5r22aBKw9_UXkwkppK4uisf1B
"""

# exercise 1
# author: Daue
# state: ongoing

# exercise 1
# author: BS
# state: ongoing

# exercise 1
# author: BL
# state: ongoing